package monszy.services;

import java.io.IOException;
import java.sql.*;
import java.util.*;

import javax.enterprise.context.ApplicationScoped;

import monszy.project.*;



@ApplicationScoped
public class ProductDBManager {

	private Connection conn;
	private Statement stmt;
	private PreparedStatement addProductStmt;
	private PreparedStatement getProductStmt;
	private PreparedStatement deleteAllProductStmt;
	private PreparedStatement findProductByNameStmt;
	private PreparedStatement findProductByTypeStmt;
	private PreparedStatement deleteProductStmt;
	
	List<Integer> listID = new ArrayList<Integer>();
	
	public ProductDBManager() 
	{
		try 
		{
			
			conn = DriverManager
					.getConnection("jdbc:hsqldb:hsql://localhost/workdb");

			stmt = conn.createStatement();
			boolean ProductTableExists = false;

			ResultSet rs = conn.getMetaData().getTables(null, null, null, null);

			while (rs.next()) 
			{
				if ("Product".equalsIgnoreCase(rs.getString("TABLE_NAME"))) 
				{
					ProductTableExists = true;
					break;
				}
			}

			if (!ProductTableExists) 
			{
				stmt.executeUpdate("CREATE TABLE Product(id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,name varchar(40), productType varchar(20), releaseYear integer, price integer)");
			}


			addProductStmt = conn.prepareStatement("INSERT INTO Product (name, productType, releaseYear, price) VALUES (?, ?, ?, ?)");

			getProductStmt = conn.prepareStatement("SELECT * FROM Product");
			
			deleteAllProductStmt = conn.prepareStatement("DELETE FROM Product");
			
			findProductByNameStmt = conn.prepareStatement("SELECT id FROM product WHERE name = ?");
			
			findProductByTypeStmt = conn.prepareStatement("SELECT id FROM product WHERE productType = ?");
			
			deleteProductStmt = conn.prepareStatement("DELETE FROM product WHERE id = ?");
		} 
		catch (SQLException e) 
		{

			e.printStackTrace();
		}
	}

	public void addProduct(Product Product) 
	{
		try 
		{
			addProductStmt.setString(1, Product.getName());
			addProductStmt.setString(2, Product.getProductType().toString());
			addProductStmt.setInt(3, Product.getReleaseYear());
			addProductStmt.setInt(4, Product.getPrice());
			addProductStmt.executeUpdate();
		} 
		catch (SQLException e) 
		{

			e.printStackTrace();
		}

	}

	public List<Product> getAllProducts() 
	{
		List<Product> Products = new ArrayList<Product>();
		try 
		{
			ResultSet rs = getProductStmt.executeQuery();
			while (rs.next()) 
			{
				ProductType productType = null;
				if (rs.getString("productType").equals("Camera"))
					productType = ProductType.Camera;
				if (rs.getString("productType").equals("Film"))
					productType = ProductType.Film;
				if (rs.getString("productType").equals("Computer"))
					productType = ProductType.Computer;
			
				
				Products.add(new Product(rs.getString("name"),productType,rs.getInt("releaseYear"),rs.getInt("price")));
			}

		} 
		catch (SQLException e) 
		{
			e.printStackTrace();
		}
		return Products;
	}

	public void deleteAllProduct() 
	{
		try 
		{
			deleteAllProductStmt.executeUpdate();
		} 
		catch (SQLException e) 
		{
			e.printStackTrace();
		}
	}
	
	public List<Integer> findProductByName(String name)
	{
		try 
		{
			List<Integer> result = new ArrayList<Integer>();
			findProductByNameStmt.setString(1, name);
			ResultSet rs = findProductByNameStmt.executeQuery();
			while (rs.next())
				result.add(rs.getInt("ID"));	
			return result;
		} 
		catch (SQLException e) 
		{
			e.printStackTrace();
		}
		return null;
	}
	
	public List<Integer> findProductByType(ProductType productType)
	{
		try 
		{
			List<Integer> result = new ArrayList<Integer>();
			findProductByTypeStmt.setString(1, productType.toString());
			ResultSet rs = findProductByTypeStmt.executeQuery();
			while (rs.next())
				result.add(rs.getInt("ID"));
			return result;
		} 
		catch (SQLException e) 
		{
			e.printStackTrace();
		}
		return null;
	}
	
	public void deleteProduct(List<Integer> list)
	{
		try 
		{
			for (Integer id : list)
			{
				deleteProductStmt.setInt(1, id);
				deleteProductStmt.executeUpdate();
			}
		} 
		catch (SQLException e) 
		{
			e.printStackTrace();
		}
	}
	
	public void printProductWithCondition(List<Product> listProduct,Condition condition)
	{
		for (Product product : listProduct)
		{
			if (condition.getCondition(product))
			{
				System.out.println("Name: " + product.getName() + "\tProductType: " + product.getProductType() + "\tReleasedYear: " + product.getReleaseYear() + "\tPrice: " + product.getPrice());
			}
		}
	}
	


}
